version: '3'
services:

  #PHP Service
  appnb:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: appnb
    restart: unless-stopped
    tty: false
    environment:
      SERVICE_NAME: appnb
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - nb-app-network

  #Nginx Service
  nbwebserver:
    image: nginx:alpine
    container_name: nb
    restart: unless-stopped
    tty: true
    ports:
      - "9700:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - nb-app-network

  #MySQL Service
  dbnb:
    image: mysql:5.7.22
    container_name: dbnb
    restart: unless-stopped
    tty: false
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: news
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - nb-app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - nb-app-network
    depends_on:
      - dbnb
    environment:
      PMA_HOST: dbnb
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "2700:80"
  mailhognb:
    container_name: mailhognb
    networks:
      - nb-app-network
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
#Docker Networks
networks:
  nb-app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
